name: Check
on: [ pull_request, push ]
jobs:
  check:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: "temurin"
        cache: "gradle"
    - name: Check
      run: ./gradlew --info --stacktrace test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: tests
        path: ./build/reports/tests/test
    - name: Generate JaCoCo test report
      run: ./gradlew jacocoTestReport coveralls
    - uses: actions/upload-artifact@v4
      with:
        name: jacoco
        path: ./build/reports/jacoco/test
